### ISSUE TITLE
Having issues with this code

### ISSUE THREAD

**Issue by seerathsethi** [seerathsethi/code-a-website#1]
![Screenshot 2021-07-06 223615](https://user-images.githubusercontent.com/83778201/124640156-a0e37580-deaa-11eb-91d3-2dd40ee760eb.png)

Hi 
I am having issues with this code. I tried many times to change this index HTML code. But it shows the same thing on markbot.

@abhaysharma
@anna-pokhilenko

**Comment by anna-pokhilenko** [comment]
Hello)
There are the fixes:

1. Change the title of one of your index.html file. You have two of the same titles and it confuses Markbot. I added an example of a new title you can use. <img width="720" alt="Screen Shot 2021-07-06 at 1 12 36 PM" src="https://user-images.githubusercontent.com/55008926/124640743-d614a700-de5b-11eb-88ca-252bedb93ba8.png">
2. On your berries pages, there are some path adjustments to be made to make it right. 
<img width="864" alt="Screen Shot 2021-07-06 at 1 18 09 PM" src="https://user-images.githubusercontent.com/55008926/124641492-c6499280-de5c-11eb-9870-908a49d0cbbe.png">
<img width="863" alt="Screen Shot 2021-07-06 at 1 23 49 PM" src="https://user-images.githubusercontent.com/55008926/124642081-69021100-de5d-11eb-9ecd-cc3300c1c97b.png">
<img width="864" alt="Screen Shot 2021-07-06 at 1 24 26 PM" src="https://user-images.githubusercontent.com/55008926/124642142-7f0fd180-de5d-11eb-88f7-adfb4272b3c1.png">
<img width="878" alt="Screen Shot 2021-07-06 at 1 25 09 PM" src="https://user-images.githubusercontent.com/55008926/124642218-9949af80-de5d-11eb-8a70-bba9bea679f1.png">
<img width="851" alt="Screen Shot 2021-07-06 at 1 26 06 PM" src="https://user-images.githubusercontent.com/55008926/124642337-bb433200-de5d-11eb-8715-89b28982eeba.png">

This should let you pass!
